### ISSUE TITLE
Update recipes to encourage usage

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/SBM-BoneTorch#6]
As of SBM-BoneTorch-1.7.10-0.0.1b6, 1 bone + 1 coal gives 4 torches, same vanilla.
This doesn't encourage to use it since bone is generally harder to come by.
Also, we could integrate with other mods:
- GC adds coal nugget-like item that could be leveraged here:
    1 coal -> 8 fragmented
    1 charcoal -> 4 fragmented carbons.
- Mekanism adds Compressed carbon through enrichment chamber

Proposed recipes:
 1 bone + 1 coal gives 6 bone torches (on the go torches, cheaper than vanilla)
 1 bone + 4 fragmented carbons gives 8 bone torches (requires crafting table, but gives more torches)
 2 cobblestone + 1 coal gives 3 torches (on the go torches)
etc.

**Comment by bl4ckscor3** [comment]
The idea behind the mod was being able to create torches in the nether without access to wood. Since 1.16 this is no longer necessary, however for decorative purposes the torches are still useful. The recipe should yield the same amount as it's now a purely cosmetic torch and is not supposed to provide any other benefit over vanilla torches.
